services:
  portal_postgres:
    profiles:
      - ''
    ports:
      - "${PORTAL_POSTGRES_PORT:-12001}:5432"
    restart: unless-stopped

  portal_backend:
    pull_policy: never
    image: portal_backend
    ports:
      - "${PORTAL_BACKEND_PORT:-12002}:80"
    volumes:
      - ./:/srv/
    profiles:
      - ''
    command: start-debug.sh
    restart: unless-stopped
