services:
  portal_postgres:
    profiles:
      - ''
    ports:
      - "12001:5432"
    restart: unless-stopped

  portal_backend:
    pull_policy: never
    image: portal_backend
    ports:
      - "12002:80"
    volumes:
      - ./:/srv/
    profiles:
      - ''
    command: start-debug.sh
    restart: unless-stopped
