[tool.mypy]
mypy_path = "stubs"
python_version = "3.12"

[tool.black]
line-length = 120
target-version = ['py312']

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]
asyncio_default_fixture_loop_scope = "session"
asyncio_mode = "auto"

[tool.flake8]
ignore = ['E203', 'D203', 'E501', 'W503']
exclude = [
        '.git',
        '__pycache__',
        'docs/source/conf.py',
        'old',
        'build',
        'dist',
        '.venv',
]
max-complexity = 25
