"""registered flag

Revision ID: ae5021f2361f
Revises: 34661e234331
Create Date: 2025-03-19 13:56:56.828783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5021f2361f'
down_revision: Union[str, None] = '34661e234331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_registered', sa.Boolean(), nullable=True))
    op.execute("""UPDATE users SET is_registered = wallet_address IS NOT NULL""")
    op.alter_column('users', 'is_registered', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_registered')
    # ### end Alembic commands ###
