"""agent system prompt

Revision ID: 65d590ab80ce
Revises: cf28854c825d
Create Date: 2025-03-14 13:41:21.539604

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.orm import Session
from src.prompts.default import default_prompt


# revision identifiers, used by Alembic.
revision: str = '65d590ab80ce'
down_revision: Union[str, None] = 'cf28854c825d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

session = Session(op.get_bind())


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    query = text("UPDATE agents SET system_prompt = :prompt").params(prompt=default_prompt)
    session.execute(query)
    op.execute("UPDATE agents SET model = 'deepseek-chat', provider = 'DeepSeek'")
    op.alter_column('agents', 'system_prompt', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'system_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
