"""make user wallet address nullable

Revision ID: 34661e234331
Revises: 65d590ab80ce
Create Date: 2025-03-19 02:31:16.027258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34661e234331'
down_revision: Union[str, None] = '65d590ab80ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
