"""add mail-confirmation status.

Revision ID: 1a669b6ad184
Revises: 60801c9268cd
Create Date: 2025-05-14 09:43:03.041361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "1a669b6ad184"
down_revision: Union[str, None] = "60801c9268cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "is_email_confirmed",
            sa.Boolean(),
            nullable=False,
            server_default=text("false"),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_email_confirmed")
    # ### end Alembic commands ###
