"""server logo

Revision ID: cf28854c825d
Revises: cb17d2a786df
Create Date: 2025-03-07 02:37:27.253200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf28854c825d'
down_revision: Union[str, None] = 'cb17d2a786df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM arp_servers;")
    op.add_column('arp_servers', sa.Column('logo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arp_servers', 'logo')
    # ### end Alembic commands ###
