"""add transport-protocol to server.

Revision ID: c51e6bac01a4
Revises: 1992cca4732c
Create Date: 2025-06-05 10:30:46.485115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c51e6bac01a4"
down_revision: Union[str, None] = "1992cca4732c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("arp_servers", sa.Column("transport_protocol", sa.String(), nullable=True))
    op.execute(sa.text("UPDATE arp_servers SET transport_protocol='SSE'"))
    op.alter_column("arp_servers", "transport_protocol", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("arp_servers", "transport_protocol")
    # ### end Alembic commands ###
