"""removed foreignkey constraint at user-id field.

Revision ID: fedfa043239a
Revises: 9170e89a926b
Create Date: 2025-05-28 11:00:20.963268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedfa043239a'
down_revision: Union[str, None] = '9170e89a926b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agents_user_id_fkey', 'agents', type_='foreignkey')
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('agents_user_id_fkey', 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
