"""arp_servers

Revision ID: eee81c277d6a
Revises: 88ae20c08c7e
Create Date: 2025-03-01 13:51:58.793330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eee81c277d6a'
down_revision: Union[str, None] = '88ae20c08c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'arp_servers',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arp_servers_id'), 'arp_servers', ['id'], unique=True)
    op.create_index(op.f('ix_arp_servers_name'), 'arp_servers', ['name'], unique=False)
    op.create_table(
        'agents_arp_servers',
        sa.Column('agent_id', sa.String(), nullable=False),
        sa.Column('server_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['server_id'], ['arp_servers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('agent_id', 'server_id')
    )
    op.drop_column('agents', 'mcp_server')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('mcp_server', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('agents_arp_servers')
    op.drop_index(op.f('ix_arp_servers_id'), table_name='arp_servers')
    op.drop_table('arp_servers')
    # ### end Alembic commands ###
